
#ifndef PROJECT_CONF_H_
#define PROJECT_CONF_H_
#if 0
#define LOG_LEVEL_APP LOG_LEVEL_DBG

#define LOG_CONF_LEVEL_RPL LOG_LEVEL_DBG
#define LOG_CONF_LEVEL_IPV6 LOG_LEVEL_DBG
#endif

//#define LOG_LEVEL_APP LOG_LEVEL_DBG
//
//#define LOG_CONF_LEVEL_RPL LOG_LEVEL_DBG
//#define LOG_CONF_LEVEL_IPV6 LOG_LEVEL_DBG
//#define LOG_CONF_LEVEL_NULLNET LOG_LEVEL_DBG

#endif /* PROJECT_CONF_H_ */
